### PR TITLE
reading whole buffer to workaround incorrect headers

### LINKED ISSUE #159: Support correct unzipping of IncorrectHeaders.zip
File with Incorrect Headers:
[IncorrectHeaders.zip](https://github.com/nmoinvaz/minizip/files/1356685/IncorrectHeaders.zip)

Unzipping it is supposed to give a 59 bytes file ending by _Julius Parishy_.

Applications that succeed at unzipping it on macOS:
* /usr/bin/unzip 6.00 of 20 April 2009 succeeds
* Archive Utility 10.10 (81) succeeds
* The Unarchiver 3.11.3 (115) succeeds

Applications that fail at unzipping it on macOS:
* MiniUnz 1.2.0 fails, as resulting file is truncated to 50 bytes and is ending by _Julius_ only. Logs:
>$ ./miniunz IncorrectHeaders.zip 
MiniUnz 1.2.0, demo of zLib + Unz package
more info at https://github.com/nmoinvaz/minizip
>
>IncorrectHeaders.zip opened
creating directory: IncorrectHeaders/
 extracting: IncorrectHeaders/Readme.txt
error -5 with zipfile in unzReadCurrentFile
error -105 with zipfile in unzCloseCurrentFile
error -5 with zipfile in unzGoToNextFile

### PR DESCRIPTION
**Pull request by Coeur**
Fix #159 for dev branch

### CODE REVIEW

**Comment by nmoinvaz** [comment]
The reason I have this code is to prevent the decompression stream from reading more than it should. If it reads more than it should then the ars encryption stream will not be able to read the auto code at the end of the file in the zip.

**Comment by Coeur** [comment]
Are you sure?
I've implemented this change in SSZipArchive 2.1.1 and zipping/unzipping with AES is still working (our test suite passes).

**Comment by nmoinvaz** [comment]
It is a difficult problem. It might be best to fork minizip 1.2 for your needs.

**Comment by nmoinvaz** [comment]
I have made a fix for 2.0 into the dev branch. Looks like my initial comment may have been incorrect.

**Pull request closed without merging**
