### PR TITLE
Added unzseek to be able to seek in zip files that have the storage c…

### PR DESCRIPTION
**Pull request by woutervd**
Added unzseek to be able to seek in zip files that have the storage compression method.
I am using this to seek in an APK file on Android.

### CODE REVIEW

**Comment by woutervd** [comment]
It has been a while since I put out this pull request. Any chance it will be considered? Or are there changes needed, or it just simply something you do not wish to support?

**Comment by nmoinvaz** [comment]
I am still considering it. Thank you.

**Comment by nmoinvaz** [comment]
Would you be able to add support for the origin parameter that is common with seek functions?

**Comment by woutervd** [comment]
Yes I can do that.
SEEK_SET, SEEK_CUR, or SEEK_END would then best be represented by the existing ZLIB_FILEFUNC_SEEK_CUR (1), ZLIB_FILEFUNC_SEEK_END (2) and ZLIB_FILEFUNC_SEEK_SET (0) ?

**Comment by nmoinvaz** [comment]
Cool. It would be best to use SEEK_SET, SEEK_CUR, and SEEK_END because it is an outward facing function and those ZLIB #define's are internal.

**Comment by woutervd** [comment]
It has been committed :)

**Comment by nmoinvaz** [comment]
Thank you!

**Comment by roussec** [comment]
I am not sure if this ever worked. Starting in line 1897 contains the following code

`   if (pfile_in_zip_read_info->compression_method != 0)
       return UNZ_ERRNO;` 

But is compression_method not always Z_DEFLATED (8)? What makes sense to check would be compression level to be 0 but I am not sure if this info is avaiable.

**Pull request merged**
