### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/nmoinvaz/minizip/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/nmoinvaz/minizip).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Is there a way to ignore alerts without having to add a comment?

**Comment by xcorail** [comment]
Hi @nmoinvaz 

One precision: 
* By default, LGTM will tentatively poll your repo once a day, and analyze all commits most recent first
* But our recommended usage is to use automated code review, by activating Pull Request integration. LGTM will analyze the Pull Requests immediately, and report any new problem (or any new fix) directly within the PR. It's a [one click operation](https://lgtm.com/projects/g/nmoinvaz/minizip/ci/), and free for public repos.

Cheers

**Comment by nmoinvaz** [comment]
I have merged in one of the badges. Thanks. Is it possible to get LGTM to check always the dev branch?

**Comment by xcorail** [comment]
Hi @nmoinvaz 
We currently analyze the default branch declared on GitHub. 
What is the branch where you actually accept Pull Requests?

**Comment by nmoinvaz** [comment]
I used to have an A rating with the same number of issues, now I have a C rating. I think maybe it is time to remove the badge.

**Comment by xcorail** [comment]
Hey

That's strange.
Let me have a look whether there is something odd on our end.

Cheers
Xavier

**Comment by nmoinvaz** [comment]
Did you just start checking localtime()? Maybe that is it. Well I have fixed it in my dev branch.

**Comment by nmoinvaz** [comment]
It would be great that as part of the GitHub LGTM app, I could set lines to ignore or files to ignore. Or even if I logged into LGTM and I could set it there. But I don't really want to set it in the source code. I'm going to try the LGTM app for the project as it seems good. I will probably keep the badge perhaps now that localtime() is fixed..

**Comment by Coeur** [comment]
> Le dim. 28 avr. 2019 à 18:32

So French. :D

**Comment by xcorail** [comment]
Hi @nmoinvaz 

> But I don't really want to set it in the source code

Do I understand well that you don't want to create the `lgtm.yml` configuration file in your repo to exclude files or queries, as I suggested in my first comment? Could you please elaborate on that and tell me what you don't like with this solution? (intrusion in your code? UX? ...)

> I'm going to try the LGTM app for the project as it seems good

Looking forward to reading your feedback!

**Comment by nmoinvaz** [comment]
Yes, it would be the intrusion into the code and putting comments on each line for the analyzer to ignore. I suppose it is not entirely uncommon though, for example right now I use `MZ_UNUSED` macro for the compiler to ignore a unused variable warning. After some research it seems that other "linters" or analyzers use comments too - but compiler warnings are usually disabled via some macro or #define - so I think it is okay. 

I just added lgtm.yml as you proposed. I am trying to exclude all the FIXME warnings.
https://github.com/nmoinvaz/minizip/blob/dev/lgtm.yml

**Comment by nmoinvaz** [comment]
I added LGTM app to GitHub project and I am happy with it after seeing it analyzer the first pull request. It seems that it has the ability to check the code in the dev branch, but the LGTM.com website doesn't separate code quality per branch. Btw, do you have any plans on creating a GitLab app as well? So far so good, keep up the good work!

**Comment by nmoinvaz** [comment]
@xcorail has something changed? It seems .lgtm files having no affect. I have external cwes mentioned in there, but they still show up as alerts in lgtm.com

**Pull request merged**
