### PR TITLE
Support building on RISC OS

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Hi. Why is it necessary for `_GNU_SOURCE_`? Is there a function that is not available?

**Comment by ccawley2011** [comment]
> Why is it necessary for _GNU_SOURCE_? Is there a function that is not available?

It's needed for `lstat()`.

**Comment by nmoinvaz** [comment]
I'm surprised `-D_POSIX_C_SOURCE=200112L` doesn't solve it. Does `_BSD_SOURCE` work? The thing is I don't see `_GNU_SOURCE` in http://man7.org/linux/man-pages/man2/stat.2.html

**Comment by ccawley2011** [comment]
It appears that the issue is that [`features.h`](https://www.riscos.info/websvn/filedetails.php?repname=gccsdk&path=%2Ftrunk%2Fgcc4%2Frecipe%2Ffiles%2Fgcc%2Flibunixlib%2Finclude%2Ffeatures.h) on RISC OS defines `__USE_XOPEN2K` when `_POSIX_C_SOURCE` is greater than or equal to 200112L, but not `__USE_XOPEN_EXTENDED`, which is needed by lstat. I've submitted a patch for this [here](https://www.riscos.info/pipermail/gcc/2019-August/006835.html), and removed the addition of `_GNU_SOURCE` from this PR, since using `lstat` when `__USE_XOPEN_EXTENDED`  is not set will just result in a warning.

**Comment by nmoinvaz** [comment]
Sounds great. Thanks!

**Pull request merged**
