### PR TITLE
proper min/max

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Reference: https://stackoverflow.com/questions/3437404/min-and-max-in-c

**Comment by nmoinvaz** [comment]
__typeof__ des not appear to be supported on MSVC.

**Comment by Coeur** [comment]
using `decltype` instead of `__typeof__` when it's WINDOWS should solve it. But I don't have any Windows machine to verify. Could you try?

**Comment by nmoinvaz** [comment]
It doesn't appear to be working, because decltype is a newer thing and I think only part of C++11.

**Comment by Coeur** [comment]
OK, then let's drop this pull request, it's not that important.

**Pull request closed without merging**
