### PR TITLE
Silence compiler warnings about unused parameters

### PR DESCRIPTION
**Pull request by asmaloney**

### CODE REVIEW

**Comment by asmaloney** [comment]
Any thoughts on getting this merged?  It includes a bugfix where there's a comparison to a pointer rather than the size of the contents.

**Comment by nmoinvaz** [comment]
It looks like the bug fix for the comparison was merged in some time ago along with the unused is64bitOpenFunction variable fix. I don't think I want to merge in the UNUSED macro.

**Comment by asmaloney** [comment]
OK.  Can you do something else to silence the compiler warnings then?

**Comment by nmoinvaz** [comment]
Try modifying the Makefile and changing it to:
CFLAGS=-O -I../.. -DHAVE_AES -Wno-unused-parameter

Let me know how that works out for you.

**Pull request closed without merging**
