### PR TITLE
Use lseek64 on Android

### LINKED ISSUE #488: use lseeko64 instead of fseeko on android
see https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-abi-bugs
`fseeko` variant implementation on android.
may be we can use `lseeko64` on android for better compatibility.

### PR DESCRIPTION
**Pull request by okhowang**
close #488

### CODE REVIEW

**Comment by nmoinvaz** [comment]
I think there should be a check for the android API version number, because it says on newer versions fseeko it is not needed.

**Comment by nmoinvaz** [comment]
Please review my changes to make sure they work for you. You will have to define MZ_FILE32_API in the project.

**Comment by okhowang** [comment]
according to [https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-abi-bugs](https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-abi-bugs)
> Android does not require the _LARGEFILE_SOURCE macro to be used to make fseeko and ftello available. Instead they're always available from API level 24 where they were introduced, and never available before then.

firstly, `fseeko` and `ftello` is general available from API level 24.

and `MZ_FILE32_API` seems undocumented. I should set it for platform which has no `ftello` and `fseeko`?

**Comment by okhowang** [comment]
I test with `MZ_FILE32_API` and everthing is ok.
myabe I can just set `MZ_FILE32_API` for android platform.
and this PR can enhance 64bit file ability for android?

**Comment by nmoinvaz** [comment]
I have merged into `dev`  branch. You should be able to set it easily with `-DMZ_FILE32_API=ON`.

**Pull request merged**
